### ISSUE TITLE
"tab -w foo" requires multiple attempts to close the tab

### ISSUE THREAD

**Issue by userxfce** [austinjones/tab-rs#165] opened 2020-10-04 18:12 UTC
example:
tab foo
<command1>
tab bar
<command2>
tab foo
tab -w foo
#tab -l still diplays foo/ and bar/
tab -w foo
tab -w foo
tab -w foo
tab -w foo
#tab -l finnaly only displays bar/

same behaviour when attempting to close bar

**Comment by austinjones** [comment] 2020-10-05 01:01
I just pushed v0.3.9 with some changes that may fix this, but I'm not certain that they will.

I tried testing (v0.3.8) on OSX and Ubuntu, and I couldn't reproduce it.  Does it happen consistently for you?  If you can reproduce it, could you capture the daemon log and upload it?  Here are some commands that will enable debug logging:
```
# the daemon inherits the log level from the command that launches it
tab --shutdown
tab --log debug foo 

# you can use ctrl-W to disconnect and reset the command-line log level
tab foo
tab -w foo
tab -l
```

The daemon log is at `~/.tab/daemon.log`, and you can reset the log level after you are done with another `tab --shutdown`.

**Comment by userxfce** [comment] 2020-10-10 17:45
It seems to have been fixed in the main/HEAD. It also dispays a message (undisplayed previously, namely: "Closing tab: bar/", which is nice feedback.
However, when closing the current tab (i.e. tab foo, then tab -w foo), it displays "[ERROR] ERR: TerminalEchoService/stdout: task was cancelled", which is feedback, but not that user-friendly.
I think this can be closed.

**Comment by userxfce** [comment] 2020-10-10 17:54
Same bahviour when running "tab", then 'tab -w any", which is again closing the current tab:
"CMD [ERROR] ERR: TerminalEchoService/stdout: task was cancelled" is displayed.
Closing the curent tab chould maybe ask for confirmation, or disabled, or display a more user-friendly message.

ANother point (hesitating whether to log a ticket): should a special "tab <command>" be an alternative to control-w, something like "tab --rootwindow" or "tab --disconnect"? Part because it is more convenient to type, part because it might be handy in scripts.

**Comment by austinjones** [comment] 2020-10-10 19:11
Thanks for the followup and testing on main!   I like the `tab --disconnect` idea - that seems useful (I've added #188). 

The behavior on closing the current tab is supposed to be:
```
foo/ $ tab -w foo
Closing tab: foo/

$
```

This `tab -w current-tab` case is a bit tough.  The invoked `tab` process triggers both terminal I/O and a shutdown notification at the same time.  In the outer `tab` process, I wait 25ms for any final terminal I/O before terminating, but that appears to not be enough for your terminal.  I don't think I can increase it though - I want to keep artificial delays as small as possible.

```
CMD [ERROR] ERR: TerminalEchoService/stdout: task was canceled
```
I'm going to improve this error message by adding some context.  The terminal close went through fine - but the stdout packet that contained the `Closing tab: any/` string didn't make it in time.

I'm not sure why it's happening every time for you though.  I saw it occasionally in CI jobs - and I haven't seen it since adding the 25ms shutdown delay.

**Comment by austinjones** [comment] 2020-10-10 19:29
Allright, I've improved the error message in #189.  I'm closing this issue.

**Closed by austinjones** 2020-10-10 19:29 UTC
Labels: bug

**Comment by userxfce** [comment] 2020-10-10 21:43
"I'm not sure why it's happening every time for you though" - it might be because of a heavily-customized (and heavy) prompt, based on a Bash "trap DEBUG" (basically, trapping the ENTER key).

**Comment by austinjones** [comment] 2020-10-10 22:12
Ah, that might do it :D
